hidden_size:
  - 64
  - 128
  - 256
  - 512
lr:
  - 0.01
  - 0.001
  - 0.0001
reg_lambda:
  - 0.01
  - 0.001
  - 0.0001
batch_size:
  - 32 
  - 64
  - 128
activation_func:
  - relu
  - sigmoid
  - tanh